services:
  myapp:
    image: reactui:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      API_BASE_URL: ${API_BASE_URL:-}
      API_MAIN_URL: ${API_MAIN_URL:-}
      API_HEALTH_BASE_URL: ${API_HEALTH_BASE_URL:-http://host.docker.internal:5820}
      API_HEALTH_URL: ${API_HEALTH_URL:-health}
      XAPI_KEY: ${XAPI_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
